parameters:
#    ft_default.example.class: FT\DefaultBundle\Example

services:
#    ft_default.example:
#        class: %ft_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
